### PR TITLE
Change the device class of the smart sensor from humidity to moisture

### PR DESCRIPTION
**Pull request by DNier**
Fixes https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/213

### CODE REVIEW

**Comment by grm** [comment]
Thx for the PR, I merge it. !

**Comment by Bucky2k** [comment]
Sorry, this is actually not working at all. Humidity was fine to me, why the change? Anyway, moisture is not exposed by the integration.

@grm Could you revert this PR please?
@DNier Any idea what could be wrong? The new entity shows up, but does not contain a valid state. It's not fed by the sensor

**Comment by crazyfx1** [comment]
The py-smart-gardena lib does not return "soil_moisture" but still "soil_humidity". Either change it back or adapt the library and push a new version:
https://github.com/py-smart-gardena/py-smart-gardena/blob/master/src/gardena/devices/soil_sensor.py

**Pull request merged**
